<a href="https://colab.research.google.com/github/lingpri/snowflakes/blob/master/B16Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a_scalar = np.array(10)

In [ ]:
print(a_scalar.ndim)

0


In [ ]:
a_vector = np.array([1,2,3,4,5])

In [ ]:
print(a_vector.ndim)

1


In [ ]:
a_mat = np.array([[1,2],[3,4]])

In [ ]:
print(a_mat.ndim)

2


A = $\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}$

In [ ]:
a = np.arange(1,13).reshape(4,3)

In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
print(a.shape)

(4, 3)


In [ ]:
print(a.size)

12


In [ ]:
print(a.shape[0])

4


In [ ]:
print(a.shape[1])

3


In [ ]:
b = np.arange(1,37).reshape(3,4,3)

In [ ]:
print(b)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]


In [ ]:
print(b.shape[0])

3


In [ ]:
print(b.size)

36


In [ ]:
np.random.seed(0)


In [ ]:
np.random.seed(0)
c = np.random.randint(1,30,size=(4,3))
print(c)

[[13 16 22]
 [ 1  4 28]
 [ 4  8 10]
 [20 22 19]]


In [ ]:
print(c[0:1,:])

[[13 16 22]]


In [ ]:
d = np.arange(1,10).reshape(3,3)

In [ ]:
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
e = d[0:2,1:]
print(e)

[[2 3]
 [5 6]]


In [ ]:
e[0][0] = 100

In [ ]:
print(e)

[[100   3]
 [  5   6]]


In [ ]:
print(d)

[[  1 100   3]
 [  4   5   6]
 [  7   8   9]]


In [ ]:
f = np.copy(d[0:2,1:])

In [ ]:
print(f)

[[100   3]
 [  5   6]]


In [ ]:
f[0][0] = 200

In [ ]:
print(f)

[[200   3]
 [  5   6]]


In [ ]:
print(d)

[[  1 100   3]
 [  4   5   6]
 [  7   8   9]]
